### ISSUE TITLE
Should we change the parameters for personalization_config in the yaml config file?

### ISSUE THREAD

**Issue by xiankgx** [XavierXiao/Dreambooth-Stable-Diffusion#77]
In the config file `configs/stable-diffusion/v1-finetune_unfrozen.yaml`,

```
    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        per_image_tokens: false
        num_vectors_per_token: 1
        progressive_words: False
```

Should the parameters here be changed, especially `placeholder_strings` and `initializer_words`? I'm guessing that it should not be necessary since we are not introducing any new learned embedding as in Textual Inversion.

Please enlighten me. Thank you.
